import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Aside from "./modules/Aside/Aside";
import Header from "./modules/Header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Salão da Leila",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="h-full w-full">
          <header className="h-[5%] w-full">
            <Header/>
          </header>
          <div className="h-[95%] flex w-full ">
            <div className="w-[15%] h-full">
              <Aside />
            </div>
            <main className="flex flex-1">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
